vich_uploader:
    db_driver: orm

    mappings:
        event_file:
            uri_prefix: /images/events
            upload_destination: '%upload_directory%'
        act_file:
            uri_prefix: /images/acts
            upload_destination: '%upload_directory%'
